### ISSUE TITLE
completion of flag arguments does not seem to work

### ISSUE THREAD

**Issue by andrewsav-bt** [tillig/ps-bash-completions#4]
typing: `kubectl get pods -n <TAB>`
expecting: `kubectl get pods -n mynamespace`
getting: `kubectl get pods -n -n`

**Comment by tillig** [comment]
Yup, that's [the one known issue I've included in the README.](https://github.com/tillig/ps-bash-completions#known-issues)

> # Known Issues
>
> PowerShell doesn't appear to pass _flags_ to custom argument completers. So, say you tried to do this:
>
> `kubectl apply -<TAB>`
>
> Note the `TAB` after the dash `-`. In bash you'd get completions for the flag like `-f` or `--filename`. PowerShell doesn't seem to call a custom argument completer for flags. (If you know how to make that work [let me know!](https://github.com/tillig/ps-bash-completions/issues))

**Comment by AndrewSav** [comment]
I have read this before posting the issue, and what I'm describing is quite different to what is described in readme. I do not know if the root cause is the same but the issue is definitely different. @tillig 

Can you see that it is different, now that I pointed that out, or would you like me to spell it out in more details?

**Comment by AndrewSav** [comment]
Also the diagnostic command like

>&"C:\Program Files\Git\bin\bash.exe" "/c/Users/username/Documents/WindowsPowerShell/Modules/PSBashCompletions/1.0.0/bash_completion_bridge.sh" "/c/completions/kubectl_completions.sh" "`<url-encoded-command-line`>"

that you give in readme run on `"kubectl%20get%20pods%20-n%20"` produces:

>/mnt/c/Users/asavinykh/kubectl_completions.sh: line 59: compopt: not currently executing completion function

Does this look normal to you?

**Comment by tillig** [comment]
Sort of, yeah.

So, there are actually two problems with trying to fake out bash command completion.

1. It takes a lot to manually execute completions. So much, I'll be honest, I don't understand it all. [I borrowed the actual fake-out code because it's so painful.](https://github.com/scop/bash-completion)
2. You're not actually _in bash_ so if a command recursively calls itself to generate completions, it all goes to pot.

If you actually look at `kubectl_completions.sh` I'm guessing around line 59 you see this:

`compopt -o nospace`

And that's actually in a larger method called `__kubectl_handle_reply()`.

If you look at what `__kubectl_handle_reply()` is doing, it's there to try and auto-complete the list of your namespaces by actually calling `kubectl` itself. It assumes everything is running in a single process with real completion functions wired up.

That's not what's going on, though. PowerShell has the command, it's trying to fake bash out and force a completion, and bash trying to call into other bash commands to get things done doesn't carry down enough shell context to get it to happen.

At least, that's how I understand it.

That's a really long way of saying, "I'll list this as a known issue and hopefully someone can help out." I, personally, do not know enough super-low-level shell stuff to make this happen. If you do, I'm more than happy to take a PR.

**Comment by tillig** [comment]
[Added known issue.](https://github.com/tillig/ps-bash-completions/blob/master/README.md#recursive-command-calls-dont-work)

**Comment by tillig** [comment]
I found [the source for compopt where this is actually thrown](http://git.savannah.gnu.org/cgit/bash.git/tree/builtins/complete.def#n831) if anyone is interested in digging in here. Even if we got past it, I'm not sure how we'd call commands that are potentially not in bash at all, so... YMMV.

**Comment by andrewsav-bt** [comment]
@tillig Thank you.
